version: "2"
services:
 my-wpdb:
   image: mariadb
   ports:
     - "8081:3306"
   environment:
     MYSQL_ROOT_PASSWORD: ChangeMe
 my-wp:
   image: wordpress
   volumes:
     - ./wordpress/:/var/www/html
     - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
   ports:
     - "8080:80"
   links:
     - my-wpdb:mysql
   environment:
     WORDPRESS_DB_PASSWORD: ChangeMe
